version: '3.8'

services:
  users-db:
    image: postgres:14
    container_name: users_db
    environment:
      POSTGRES_DB: divine_users
      POSTGRES_USER: divine_user
      POSTGRES_PASSWORD: user_password
    volumes:
      - users-pgdata:/var/lib/postgresql/data
    networks:
      - divine-network

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users_service
    depends_on:
      - users-db
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: users-db
      DB_PORT: 5432
      DB_DATABASE: divine_users
      DB_USERNAME: divine_user
      DB_PASSWORD: user_password
    ports:
      - "8000:8000"
    networks:
      - divine-network
    volumes:
      - ./users-service:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
  users-pgdata:

networks:
  divine-network:
    driver: bridge